# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yyy/code/ltp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yyy/code/ltp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yyy/code/ltp/CMakeFiles /home/yyy/code/ltp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yyy/code/ltp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named boost_regex

# Build rule for target.
boost_regex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boost_regex
.PHONY : boost_regex

# fast build rule for target.
boost_regex/fast:
	$(MAKE) -f thirdparty/boost/libs/regex/CMakeFiles/boost_regex.dir/build.make thirdparty/boost/libs/regex/CMakeFiles/boost_regex.dir/build
.PHONY : boost_regex/fast

#=============================================================================
# Target rules for targets named maxent_exe

# Build rule for target.
maxent_exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maxent_exe
.PHONY : maxent_exe

# fast build rule for target.
maxent_exe/fast:
	$(MAKE) -f thirdparty/maxent/CMakeFiles/maxent_exe.dir/build.make thirdparty/maxent/CMakeFiles/maxent_exe.dir/build
.PHONY : maxent_exe/fast

#=============================================================================
# Target rules for targets named maxent_lib

# Build rule for target.
maxent_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maxent_lib
.PHONY : maxent_lib

# fast build rule for target.
maxent_lib/fast:
	$(MAKE) -f thirdparty/maxent/CMakeFiles/maxent_lib.dir/build.make thirdparty/maxent/CMakeFiles/maxent_lib.dir/build
.PHONY : maxent_lib/fast

#=============================================================================
# Target rules for targets named tinyxml

# Build rule for target.
tinyxml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyxml
.PHONY : tinyxml

# fast build rule for target.
tinyxml/fast:
	$(MAKE) -f thirdparty/tinyxml/CMakeFiles/tinyxml.dir/build.make thirdparty/tinyxml/CMakeFiles/tinyxml.dir/build
.PHONY : tinyxml/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f src/__util/CMakeFiles/util.dir/build.make src/__util/CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named xml4nlp

# Build rule for target.
xml4nlp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xml4nlp
.PHONY : xml4nlp

# fast build rule for target.
xml4nlp/fast:
	$(MAKE) -f src/__xml4nlp/CMakeFiles/xml4nlp.dir/build.make src/__xml4nlp/CMakeFiles/xml4nlp.dir/build
.PHONY : xml4nlp/fast

#=============================================================================
# Target rules for targets named splitsnt

# Build rule for target.
splitsnt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 splitsnt
.PHONY : splitsnt

# fast build rule for target.
splitsnt/fast:
	$(MAKE) -f src/_split_sentence/CMakeFiles/splitsnt.dir/build.make src/_split_sentence/CMakeFiles/splitsnt.dir/build
.PHONY : splitsnt/fast

#=============================================================================
# Target rules for targets named otcws

# Build rule for target.
otcws: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 otcws
.PHONY : otcws

# fast build rule for target.
otcws/fast:
	$(MAKE) -f src/segmentor/CMakeFiles/otcws.dir/build.make src/segmentor/CMakeFiles/otcws.dir/build
.PHONY : otcws/fast

#=============================================================================
# Target rules for targets named segmentor

# Build rule for target.
segmentor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 segmentor
.PHONY : segmentor

# fast build rule for target.
segmentor/fast:
	$(MAKE) -f src/segmentor/CMakeFiles/segmentor.dir/build.make src/segmentor/CMakeFiles/segmentor.dir/build
.PHONY : segmentor/fast

#=============================================================================
# Target rules for targets named otpos

# Build rule for target.
otpos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 otpos
.PHONY : otpos

# fast build rule for target.
otpos/fast:
	$(MAKE) -f src/postagger/CMakeFiles/otpos.dir/build.make src/postagger/CMakeFiles/otpos.dir/build
.PHONY : otpos/fast

#=============================================================================
# Target rules for targets named postagger

# Build rule for target.
postagger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 postagger
.PHONY : postagger

# fast build rule for target.
postagger/fast:
	$(MAKE) -f src/postagger/CMakeFiles/postagger.dir/build.make src/postagger/CMakeFiles/postagger.dir/build
.PHONY : postagger/fast

#=============================================================================
# Target rules for targets named lgdpj

# Build rule for target.
lgdpj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lgdpj
.PHONY : lgdpj

# fast build rule for target.
lgdpj/fast:
	$(MAKE) -f src/parser/CMakeFiles/lgdpj.dir/build.make src/parser/CMakeFiles/lgdpj.dir/build
.PHONY : lgdpj/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) -f src/parser/CMakeFiles/parser.dir/build.make src/parser/CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named ner

# Build rule for target.
ner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ner
.PHONY : ner

# fast build rule for target.
ner/fast:
	$(MAKE) -f src/_ner/CMakeFiles/ner.dir/build.make src/_ner/CMakeFiles/ner.dir/build
.PHONY : ner/fast

#=============================================================================
# Target rules for targets named SRLExtract

# Build rule for target.
SRLExtract: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SRLExtract
.PHONY : SRLExtract

# fast build rule for target.
SRLExtract/fast:
	$(MAKE) -f src/_srl/CMakeFiles/SRLExtract.dir/build.make src/_srl/CMakeFiles/SRLExtract.dir/build
.PHONY : SRLExtract/fast

#=============================================================================
# Target rules for targets named SRLGetInstance

# Build rule for target.
SRLGetInstance: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SRLGetInstance
.PHONY : SRLGetInstance

# fast build rule for target.
SRLGetInstance/fast:
	$(MAKE) -f src/_srl/CMakeFiles/SRLGetInstance.dir/build.make src/_srl/CMakeFiles/SRLGetInstance.dir/build
.PHONY : SRLGetInstance/fast

#=============================================================================
# Target rules for targets named srl

# Build rule for target.
srl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srl
.PHONY : srl

# fast build rule for target.
srl/fast:
	$(MAKE) -f src/_srl/CMakeFiles/srl.dir/build.make src/_srl/CMakeFiles/srl.dir/build
.PHONY : srl/fast

#=============================================================================
# Target rules for targets named ltp_server

# Build rule for target.
ltp_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ltp_server
.PHONY : ltp_server

# fast build rule for target.
ltp_server/fast:
	$(MAKE) -f src/server/CMakeFiles/ltp_server.dir/build.make src/server/CMakeFiles/ltp_server.dir/build
.PHONY : ltp_server/fast

#=============================================================================
# Target rules for targets named ltp

# Build rule for target.
ltp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ltp
.PHONY : ltp

# fast build rule for target.
ltp/fast:
	$(MAKE) -f src/__ltp_dll/CMakeFiles/ltp.dir/build.make src/__ltp_dll/CMakeFiles/ltp.dir/build
.PHONY : ltp/fast

#=============================================================================
# Target rules for targets named ltp_test

# Build rule for target.
ltp_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ltp_test
.PHONY : ltp_test

# fast build rule for target.
ltp_test/fast:
	$(MAKE) -f test/CMakeFiles/ltp_test.dir/build.make test/CMakeFiles/ltp_test.dir/build
.PHONY : ltp_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... boost_regex"
	@echo "... maxent_exe"
	@echo "... maxent_lib"
	@echo "... tinyxml"
	@echo "... util"
	@echo "... xml4nlp"
	@echo "... splitsnt"
	@echo "... otcws"
	@echo "... segmentor"
	@echo "... otpos"
	@echo "... postagger"
	@echo "... lgdpj"
	@echo "... parser"
	@echo "... ner"
	@echo "... SRLExtract"
	@echo "... SRLGetInstance"
	@echo "... srl"
	@echo "... ltp_server"
	@echo "... ltp"
	@echo "... ltp_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

